---
- hosts: ["ubuntu","controller"] 
  tasks: 
  - name: instasll package for ubuntu server
    tags: Ubuntu
    ansible.builtin.apt:
      
      name: "{{ package_name}}"
      state: latest
       
        
    when: ansible_distribution == "Ubuntu"
  - name: uninstall package for ubuntu
    tags: Ubuntu2
    ansible.builtin.apt:
      name: " {{ package_name_2}}" 
    
      state: absent
  - name: copy default html file for site 
    tags: apache 
    ansible.builtin.copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  - name: install unzip
    tags: terraform
    ansible.builtin.package:
       name: unzip
 
  - name: install terraform
    tags: terraform
    ansible.builtin.unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
 

