---
- hosts: all
  tasks:
    - name: Create a virtual machine on the given ESXi hostname
      vmware_guest:
        hostname: "{{ item.key }}"
        username: "{{ item.value.esxi_username }}"
        password: "{{ item.value.esxi_password }}"
        validate_certs: no
        folder: "/vm/"
        name: "{{ item.value.vm_name }}"
        state: "poweredoff"
        guest_id: "centos64Guest"
        disk:
          - size_gb: 1
            type: thin
            datastore: "{{ item.value.datastore }}"
        hardware:
          memory_mb: 512
          num_cpus: 1
          scsi: "paravirtual"

        networks:
          - name: "{{ item.value.network_name }}"
            mac: "{{ item.value.mac_address }}"
            ip: "{{ item.value.ip_address }}"
            netmask: "{{ item.value.netmask }}"
            device_type: "vmxnet3"
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy_vm
    loop: "{{ esxi_hosts | dict2items }}"
    loop_control:
      loop_var: item
